config/routes.rb
Rails.application.routes.draw do
  resources :vestibulares

  get 'inicio/index'

end

app/models/vestibulare.rb
class Vestibulare < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/vestibulares_controller.rb
class VestibularesController < ApplicationController
  before_action :set_vestibulare, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @vestibulares = Vestibulare.all
    respond_with(@vestibulares)
  end

  def show
    respond_with(@vestibulare)
  end

  def new
    @vestibulare = Vestibulare.new
    respond_with(@vestibulare)
  end

  def edit
  end

  def create
    @vestibulare = Vestibulare.new(vestibulare_params)
    @vestibulare.save
    respond_with(@vestibulare)
  end

  def update
    @vestibulare.update(vestibulare_params)
    respond_with(@vestibulare)
  end

  def destroy
    @vestibulare.destroy
    respond_with(@vestibulare)
  end

  private
    def set_vestibulare
      @vestibulare = Vestibulare.find(params[:id])
    end

    def vestibulare_params
      params.require(:vestibulare).permit(:descricao, :inicio, :fim, :prazoboleto, :prova, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/vestibulares_helper.rb
module VestibularesHelper
end

app/views/inicio/index.html.erb
<h1>Inicio#index</h1>
<p>Find me in app/views/inicio/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vestibular</title>
  <%= stylesheet_link_tag    'yeti', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



  <div class="navbar navbar-default ">
     <div class="container">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
               <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                 </button>
                <a class="navbar-brand" href="#">Vestibular Faceres</a>
                 </div>
                <div class="navbar-collapse collapse">
                   <ul class="nav navbar-nav">
                      <li><a href="#">Home</a></li>
                       <li><a href="#about">Sua Inscrição</a></li>
                        <li><a href="#contact">Seus Dados</a></li>
                         </ul>
                        </div><!--/.nav-collapse -->
                       </div>
                      </div>


  <div class='container theme-showcase'>
    <%= yield %>
  </div>



</body>
</html>

app/views/layouts/cosmo.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "vestibular" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "cosmo", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse ">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Vestibular Faceres</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#about">Sua Inscrição</a></li>
            <li><a href="#contact">Seus Dados</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "cosmo" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/flatly.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "vestibular" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "flatly", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


    <%= yield %>

    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Vestibular Faceres</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#about">Sua Inscrição</a></li>
            <li><a href="#contact">Seus Contatos</a></li>

          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>


    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "flatly" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/simplex.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "vestibular" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "simplex", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>



    <!-- Fixed navbar -->
    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Bootstrap theme</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="#">Home</a></li>
            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase">

      <br><br><br>
      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "simplex" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/layouts/yeti.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "vestibular" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "yeti", :media => "all" %>

    <%= yield(:page_stylesheet) if content_for?(:page_stylesheet) %>

  </head>
  <body>


     <!-- Fixed navbar -->
    <div class="navbar navbar-default ">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Vestibular Faceres</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="#">Home</a></li>
            <li><a href="#about">Sua Inscrição</a></li>
            <li><a href="#contact">Seus Dados</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

    <div class="container theme-showcase">

      <%= yield %>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "yeti" %>
    <%= yield(:page_javascript) if content_for?(:page_javascript) %>
  </body>
</html>

app/views/vestibulares/_form.html.erb
<%= form_for @vestibulare, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :descricao, :class => 'control-label' %>
    <%= f.text_field :descricao, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :inicio, :class => 'control-label' %>
    <%= f.datetime_select :inicio, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :fim, :class => 'control-label' %>
    <%= f.datetime_select :fim, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :prazoboleto, :class => 'control-label' %>
    <%= f.date_select :prazoboleto, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :prova, :class => 'control-label' %>
    <%= f.datetime_select :prova, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label' %>
    <%= f.number_field :status, :class => 'form-control' %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                vestibulares_path, :class => 'btn' %>
  </div>
<% end %>

app/views/vestibulares/edit.html.erb
<%- model_class = Vestibulare -%>
<div class="page-header">
  <h1><%=t 'Editar Vestibular', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vestibulares/index.html.erb
<%- model_class = Vestibulare -%>
<div class="page-header">
  <h1><%=t 'Vestibulares', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= link_to t('Novo', :default => t("helpers.links.new")),
            new_vestibulare_path,
            :class => 'btn btn-default' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descricao) %></th>
      <th><%= model_class.human_attribute_name(:inicio) %></th>
      <th><%= model_class.human_attribute_name(:fim) %></th>
      <th><%= model_class.human_attribute_name(:prazoboleto) %></th>
      <th><%= model_class.human_attribute_name(:prova) %></th>
      <th><%= model_class.human_attribute_name(:status) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @vestibulares.each do |vestibulare| %>
      <tr>
        <td><%= link_to vestibulare.id, vestibulare_path(vestibulare) %></td>
        <td><%= vestibulare.descricao %></td>
        <td><%= vestibulare.inicio %></td>
        <td><%= vestibulare.fim %></td>
        <td><%= vestibulare.prazoboleto %></td>
        <td><%= vestibulare.prova %></td>
        <td><%= vestibulare.status %></td>
        <td><%=l vestibulare.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_vestibulare_path(vestibulare), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      vestibulare_path(vestibulare),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vestibulares/new.html.erb
<%- model_class = Vestibulare -%>
<div class="page-header">
  <h1><%=t 'Novo Vestibular', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/vestibulares/show.html.erb
<%- model_class = Vestibulare -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descricao) %>:</strong></dt>
  <dd><%= @vestibulare.descricao %></dd>
  <dt><strong><%= model_class.human_attribute_name(:inicio) %>:</strong></dt>
  <dd><%= @vestibulare.inicio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fim) %>:</strong></dt>
  <dd><%= @vestibulare.fim %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prazoboleto) %>:</strong></dt>
  <dd><%= @vestibulare.prazoboleto %></dd>
  <dt><strong><%= model_class.human_attribute_name(:prova) %>:</strong></dt>
  <dd><%= @vestibulare.prova %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @vestibulare.status %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              vestibulares_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_vestibulare_path(@vestibulare), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              vestibulare_path(@vestibulare),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>